spring:
  application:
    name: msemplocontrol
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:

server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-user:eureka-pass@localhost:8761/eureka
      #default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}
mq:
  queues:
    employee-queue: "employee-queue"
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  charset:
    file: ./logs/log-file.log