spring:
  application:
    name: msstore
  config:
    activate:
      on-profile: dev
    name: dev-YAML
    environment: development
    enabled: true
    servers:
      - www.abc.com
      - www.xyz.com
---
spring:
  config:
    activate:
      on-profile: test
    name: test-YAML
    environment: test
    enabled: true
    servers:
      - www.abc.com
      - www.xyz.com
---
server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    service-url:
      #default-zone:http://curso-eureka-user:curso-eureka-pass@localhost:8761/eureka
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  charset:
    file: ./logs/log-file.log