spring:
  application:
    name: msgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://cursoms-keycloak:8081/realms/MSManagerSysRealm
          issuer-uri: http://localhost:8081/realms/MSManagerSysRealm

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-user:eureka-pass@localhost:8761/eureka
      #defaultZone: http://localhost:8761/eureka
