
spring:
  application:
    name: msEmployee
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    service-url:
      #default-zone:http://curso-eureka-user:curso-eureka-pass@localhost:8761/eureka
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  charset:
    file: ./logs/log-file.log